# Generated by Django 5.0.7 on 2024-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
