# Generated by Django 5.1 on 2024-09-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_status_tipconflict_report_tip_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.specie'),
        ),
        migrations.AlterField(
            model_name='report',
            name='species_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.speciescategory'),
        ),
    ]
