# Generated by Django 5.1 on 2024-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_specie_alter_report_species_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('IA', 'În așteptare'), ('PR', 'Preluat'), ('RE', 'Rezolvat'), ('NE', 'Nesoluționat')], default='IA', max_length=2),
        ),
    ]
