# Generated by Django 5.1 on 2024-09-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_delete_status_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecieIdentificata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='numar_indivizi',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='observatii_specialist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='solutionare',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('IA', 'În așteptare'), ('PR', 'Preluat'), ('CF', 'Rezolvat - colonie fără intervenție'), ('FI', 'Rezolvat - individ izolat fără intervenție'), ('CD', 'Nesoluționat - colonie distrusă'), ('IO', 'Nesoluționat - individ izolat omorât'), ('NE', 'Nesoluționat - incert'), ('EX', 'Excludere - colonie'), ('EA', 'Excludere - colonie din anvelopare'), ('RC', 'Relocare - colonie'), ('RI', 'Relocare - individ izolat'), ('CR', 'Centru reabilitare - colonie'), ('IR', 'Centru reabilitare - individ izolat')], default='IA', max_length=2),
        ),
        migrations.AddField(
            model_name='report',
            name='specie_identificata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.specieidentificata'),
        ),
    ]
