# Generated by Django 5.1 on 2024-09-27 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_specieidentificata_report_numar_indivizi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='specie',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='species_category',
            new_name='clasa',
        ),
        migrations.RemoveField(
            model_name='report',
            name='numar_indivizi',
        ),
        migrations.RemoveField(
            model_name='report',
            name='observatii_specialist',
        ),
        migrations.RemoveField(
            model_name='report',
            name='solutionare',
        ),
        migrations.RemoveField(
            model_name='report',
            name='specie_identificata',
        ),
        migrations.RemoveField(
            model_name='report',
            name='tip_conflict',
        ),
        migrations.RenameModel(
            old_name='SpeciesCategory',
            new_name='Clasa',
        ),
        migrations.CreateModel(
            name='Ordin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasa', to='report.clasa')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='ordin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.ordin'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.status'),
        ),
        migrations.AddField(
            model_name='status',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.statuscategorie'),
        ),
        migrations.CreateModel(
            name='Voluntar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_indivizi', models.SmallIntegerField(blank=True, null=True)),
                ('observatii_specialist', models.TextField(blank=True, null=True)),
                ('solutionare', models.DateTimeField(blank=True, null=True)),
                ('sesizare', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.report')),
                ('specie_identificata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.specieidentificata')),
                ('tip_conflict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.tipconflict')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Specie',
        ),
    ]
