# Generated by Django 5.1 on 2024-09-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_status_statuscategorie_remove_report_specie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieTipConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tipconflict',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.categorietipconflict'),
        ),
    ]
