# Generated by Django 5.1 on 2024-09-27 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_categorietipconflict_tipconflict_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Sesizare',
        ),
        migrations.AddField(
            model_name='voluntar',
            name='preluare_sesizare',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
