# Generated by Django 5.1 on 2024-09-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_rename_report_sesizare_voluntar_preluare_sesizare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntar',
            name='sesizare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voluntari', to='report.sesizare'),
        ),
    ]
