# Generated by Django 5.1 on 2024-09-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_voluntar_sesizare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntar',
            name='sesizare',
        ),
        migrations.AddField(
            model_name='voluntar',
            name='sesizare',
            field=models.ManyToManyField(to='report.sesizare'),
        ),
    ]
