# Generated by Django 5.1 on 2024-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_remove_voluntar_sesizare_voluntar_sesizare'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='culoare',
            field=models.CharField(default='#f01000', max_length=7),
        ),
    ]
