# Generated by Django 5.1 on 2024-09-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_status_culoare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='culoare',
            field=models.CharField(default='bg-red-700', max_length=15),
        ),
    ]
