# Generated by Django 5.1 on 2024-09-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_alter_status_culoare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntar',
            name='sesizare',
        ),
        migrations.AddField(
            model_name='sesizare',
            name='voluntar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.voluntar'),
        ),
    ]
