# Generated by Django 5.1 on 2024-09-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_remove_voluntar_sesizare_sesizare_voluntar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntar',
            name='numar_indivizi',
        ),
        migrations.RemoveField(
            model_name='voluntar',
            name='observatii_specialist',
        ),
        migrations.RemoveField(
            model_name='voluntar',
            name='preluare_sesizare',
        ),
        migrations.RemoveField(
            model_name='voluntar',
            name='solutionare',
        ),
        migrations.RemoveField(
            model_name='voluntar',
            name='specie_identificata',
        ),
        migrations.RemoveField(
            model_name='voluntar',
            name='tip_conflict',
        ),
        migrations.CreateModel(
            name='RaportVoluntar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_indivizi', models.SmallIntegerField(blank=True, null=True)),
                ('observatii_specialist', models.TextField(blank=True, null=True)),
                ('preluare_sesizare', models.DateTimeField(blank=True, null=True)),
                ('solutionare', models.DateTimeField(blank=True, null=True)),
                ('specie_identificata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.specieidentificata')),
                ('tip_conflict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.tipconflict')),
                ('voluntar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.voluntar')),
            ],
        ),
    ]
