# Generated by Django 5.1 on 2024-09-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_remove_voluntar_numar_indivizi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesizare',
            name='voluntar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.raportvoluntar'),
        ),
    ]
