# Generated by Django 5.1 on 2024-10-01 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_alter_sesizare_voluntar'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportvoluntar',
            name='data_atribuire',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntar',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
