# Generated by Django 5.1 on 2024-10-01 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_raportvoluntar_data_atribuire_voluntar_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesizare',
            name='voluntar',
        ),
        migrations.AddField(
            model_name='raportvoluntar',
            name='sesizare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.sesizare'),
        ),
    ]
