# Generated by Django 5.1 on 2024-10-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_remove_sesizare_voluntar_raportvoluntar_sesizare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportvoluntar',
            name='tip_conflict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.tipconflict'),
        ),
    ]
