# Generated by Django 5.1 on 2024-10-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_alter_raportvoluntar_tip_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportvoluntar',
            name='voluntar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.voluntar'),
        ),
    ]
