# Generated by Django 5.1 on 2024-10-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_alter_raportvoluntar_voluntar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesizare',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='raportvoluntar',
            name='sesizare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapoarte', to='report.sesizare'),
        ),
    ]
