# Generated by Django 5.1 on 2024-10-02 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_alter_sesizare_options_alter_raportvoluntar_sesizare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportvoluntar',
            name='specie_identificata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='raport_specii', to='report.specieidentificata'),
        ),
        migrations.AlterField(
            model_name='sesizare',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sesizare_status', to='report.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_status', to='report.statuscategorie'),
        ),
        migrations.AlterField(
            model_name='voluntar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voluntari', to=settings.AUTH_USER_MODEL),
        ),
    ]
