# Generated by Django 5.1 on 2024-10-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_alter_raportvoluntar_specie_identificata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipconflict',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorii_conflict', to='report.categorietipconflict'),
        ),
    ]
