# Generated by Django 5.1 on 2024-10-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_alter_tipconflict_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportvoluntar',
            name='voluntar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voluntari', to='report.voluntar'),
        ),
    ]
