# Generated by Django 5.1 on 2024-10-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_alter_raportvoluntar_voluntar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportvoluntar',
            name='voluntar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voluntari_raport', to='report.voluntar'),
        ),
    ]
