# Generated by Django 5.1 on 2024-10-03 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_alter_raportvoluntar_voluntar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raportvoluntar',
            name='sesizare',
        ),
        migrations.CreateModel(
            name='Dashborad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.raportvoluntar')),
                ('sesizare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.sesizare')),
            ],
        ),
    ]
