# Generated by Django 5.1 on 2024-10-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_remove_raportvoluntar_sesizare_dashborad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashborad',
            new_name='Dashboard',
        ),
    ]
