# Generated by Django 5.1 on 2024-10-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_rename_dashborad_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportvoluntar',
            name='sesizare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.sesizare'),
        ),
        migrations.AlterField(
            model_name='raportvoluntar',
            name='voluntar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.voluntar'),
        ),
    ]
