# Generated by Django 5.1 on 2024-10-08 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_raportvoluntar_sesizare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raportvoluntar',
            name='data_atribuire',
        ),
        migrations.RemoveField(
            model_name='raportvoluntar',
            name='preluare_sesizare',
        ),
        migrations.RemoveField(
            model_name='raportvoluntar',
            name='solutionare',
        ),
        migrations.CreateModel(
            name='RaportVoluntarMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuit_la', models.DateTimeField(auto_now_add=True, null=True)),
                ('preluare_sesizare', models.DateTimeField(blank=True, null=True)),
                ('solutionat_la', models.DateTimeField(blank=True, null=True)),
                ('modificat_la', models.DateTimeField(blank=True, null=True)),
                ('atribuit_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuit', to=settings.AUTH_USER_MODEL)),
                ('modificat_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='raportvoluntar',
            name='raport_meta',
            field=models.ManyToManyField(to='report.raportvoluntarmeta'),
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
