# Generated by Django 5.1 on 2024-10-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0030_remove_raportvoluntar_data_atribuire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportvoluntar',
            name='raport_meta',
            field=models.ManyToManyField(blank=True, to='report.raportvoluntarmeta'),
        ),
    ]
