# Generated by Django 5.1 on 2024-10-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0032_remove_raportvoluntar_raport_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalraportvoluntar',
            name='preluare_sesizare',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raportvoluntar',
            name='preluare_sesizare',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
