# Generated by Django 5.1 on 2024-10-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_historicalraportvoluntar_preluare_sesizare_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaportVoluntarMeta',
        ),
    ]
