# Generated by Django 5.1 on 2025-06-22 14:29

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsesizare',
            name='email',
            field=models.EmailField(blank=True, default='-', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalsesizare',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RO'),
        ),
        migrations.AddField(
            model_name='sesizare',
            name='email',
            field=models.EmailField(blank=True, default='-', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sesizare',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RO'),
        ),
    ]
