# Generated by Django 5.1 on 2025-06-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_historicalsesizare_email_historicalsesizare_telefon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsesizare',
            name='clasa',
        ),
        migrations.RemoveField(
            model_name='historicalsesizare',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsesizare',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalsesizare',
            name='ordin',
        ),
        migrations.RemoveField(
            model_name='historicalsesizare',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalsesizare',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalRaportVoluntar',
        ),
        migrations.DeleteModel(
            name='HistoricalSesizare',
        ),
    ]
