# Generated by Django 5.1 on 2025-06-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_historicalsesizare_clasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesizare',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
